"""Kaggle shard r5-n200-seeds8-15: arms=primary,control, N=200, seeds=8-15.

Generated by scripts/make_kaggle_shards.py.  CPU only, internet required.
"""

import os
import subprocess
import sys

REPO = "https://github.com/Thom-320/nma-motor-rnn-connectivity.git"
BRANCH = "robustness-2026-10"
WORK = "/kaggle/working"
SRC = os.path.join(WORK, "src-repo")

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

if not os.path.isdir(SRC):
    subprocess.run(["git", "clone", "--depth", "1", "--branch", BRANCH, REPO, SRC], check=True)
commit = subprocess.run(["git", "-C", SRC, "rev-parse", "HEAD"], check=True,
                        capture_output=True, text=True).stdout.strip()
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "--no-deps", SRC], check=True)
with open(os.path.join(WORK, "SOURCE_COMMIT.txt"), "w") as handle:
    handle.write(commit + "\n")
print("installed", REPO, BRANCH, commit, flush=True)

subprocess.run(
    [sys.executable, "-m", "nma_motor_rnn.robustness", "run",
     "--arms", "primary,control", "--n-units", "200", "--seeds", "8-15",
     "--out", os.path.join(WORK, "robustness"), "--workers", str(os.cpu_count() or 4)],
    check=True,
)
subprocess.run(
    [sys.executable, "-m", "nma_motor_rnn.robustness", "collect",
     "--out", os.path.join(WORK, "robustness")],
    check=True,
)
subprocess.run(["rm", "-rf", SRC], check=True)
print("done; CSVs are in /kaggle/working/robustness", flush=True)
