"""Write the self-contained Kaggle shards under ``kaggle/``.

Each shard is one private CPU kernel (no GPU, internet on) that clones this
repository at ``BRANCH``, installs it, runs one slice of the robustness grid
with four workers and leaves CSVs in ``/kaggle/working``.  Replace
``KAGGLE_USERNAME`` in every ``kernel-metadata.json`` before pushing with
``kaggle kernels push -p kaggle/<shard>``.  Download the outputs and copy the
``robustness/raw/<arm>_N<N>/`` folders into ``results/robustness/raw/``, then
run ``python -m nma_motor_rnn.robustness collect`` and
``python scripts/analyze_robustness.py``; finished tasks are never re-run.
"""

import json
from pathlib import Path

REPO = "https://github.com/Thom-320/nma-motor-rnn-connectivity.git"
BRANCH = "robustness-2026-10"

SHARDS = {
    "r4-n400-seeds0-3": ("primary,control", 400, "0-3"),
    "r4-n400-seeds4-7": ("primary,control", 400, "4-7"),
    "r4-n100-seeds0-7": ("primary,control", 100, "0-7"),
    "r5-n200-seeds8-15": ("primary,control", 200, "8-15"),
}

TEMPLATE = '''"""Kaggle shard {name}: arms={arms}, N={n_units}, seeds={seeds}.

Generated by scripts/make_kaggle_shards.py.  CPU only, internet required.
"""

import os
import subprocess
import sys

REPO = "{repo}"
BRANCH = "{branch}"
WORK = "/kaggle/working"
SRC = os.path.join(WORK, "src-repo")

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"

if not os.path.isdir(SRC):
    subprocess.run(["git", "clone", "--depth", "1", "--branch", BRANCH, REPO, SRC], check=True)
commit = subprocess.run(["git", "-C", SRC, "rev-parse", "HEAD"], check=True,
                        capture_output=True, text=True).stdout.strip()
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "--no-deps", SRC], check=True)
with open(os.path.join(WORK, "SOURCE_COMMIT.txt"), "w") as handle:
    handle.write(commit + "\\n")
print("installed", REPO, BRANCH, commit, flush=True)

subprocess.run(
    [sys.executable, "-m", "nma_motor_rnn.robustness", "run",
     "--arms", "{arms}", "--n-units", "{n_units}", "--seeds", "{seeds}",
     "--out", os.path.join(WORK, "robustness"), "--workers", str(os.cpu_count() or 4)],
    check=True,
)
subprocess.run(
    [sys.executable, "-m", "nma_motor_rnn.robustness", "collect",
     "--out", os.path.join(WORK, "robustness")],
    check=True,
)
subprocess.run(["rm", "-rf", SRC], check=True)
print("done; CSVs are in /kaggle/working/robustness", flush=True)
'''


def main() -> None:
    root = Path("kaggle")
    for name, (arms, n_units, seeds) in SHARDS.items():
        folder = root / name
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "run.py").write_text(TEMPLATE.format(
            name=name, arms=arms, n_units=n_units, seeds=seeds, repo=REPO, branch=BRANCH))
        metadata = {
            "id": f"KAGGLE_USERNAME/nma-motor-rnn-{name}",
            "title": f"nma-motor-rnn {name}",
            "code_file": "run.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": False,
            "enable_tpu": False,
            "enable_internet": True,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": [],
            "model_sources": [],
        }
        (folder / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
        print(folder)


if __name__ == "__main__":
    main()
